export const USER_NAME_COMMAND = "--username=";
export const WELCOME_MESSAGE_TEXT = "Welcome to the File Manager, ";
export const CURRENT_PATH_MESSAGE = "You are currently in ";

export const UP_DIRECTORY_COMMAND = "up";
export const DIRECTORY_LIST = "ls";
export const CHANGE_DIRECTORY = "cd";
export const READ_FILE = "cat";
export const CREATE_FILE = "add";
export const RENAME_FILE = "rn";
export const COPY_FILE = "cp";
export const MOVE_FILE = "mv";
export const REMOVE_FILE = "rm";
export const OPERATING_SYSTEM = "os";
export const OPERATING_SYSTEM_EOL = "EOL";
export const OPERATING_SYSTEM_CPUS = "cpus";
export const OPERATING_SYSTEM_HOMEDIR = "homedir";
export const OPERATING_SYSTEM_USERNAME = "username";
export const OPERATING_SYSTEM_ARCHITECTURE = "architecture";
export const GET_HASH = "hash";
export const COMPRESS = "compress";
export const DECOMPRESS = "decompress";
export const EXIT = ".exit";
export const WRONG_COMMAND = "Invalid input";
export const DEFAULT_PROMPT = "Write your command here> ";
export const ERROR_MESSAGE = "Operation failed";
export const EXIT_MESSAGE = "Thank you for using File Manager, ";
